Up and running with Sample Spring-Cloud based Hystrix demo app
--------------------------------------------------------------

There are two ways to run the entire application:

* On Local Machine
* Using Docker

On Local Machine
~~~~~~~~~~~~~~~~
Running it all local is simple, do the following in sequence, in four different terminal windows:

.Start up Eureka
[source,java]
----
cd sample-hystrix-eureka
mvn spring-boot:run
----


.Start up Config server
[source,java]
----
cd sample-hystrix-config
mvn spring-boot:run
----

.Start up Sample Service
[source,java]
----
cd sample-hystrix-service
mvn spring-boot:run
----

.Start up Aggregate Application
[source,java]
----
cd sample-hystrix-aggregate
mvn spring-boot:run
----

.Start up Gateway Application
[source,java]
----
cd sample-hystrix-gateway
mvn spring-boot:run
----

.Start up Monitoring Application
[source,java]
----
cd sample-hystrix-monitor
mvn spring-boot:run
----


If all the applications have come up cleanly, the following endpoints are available:

* Endpoints of the gateway application which forwards requests to the sample-hystrix-aggregate: Try http://localhost:8080/sample-hystrix-aggregate/hello
* Eureka endpoint at http://localhost:8761
* Hystrix dashboard at http://localhost:8989/hystrix
* Turbine stream which aggregates information from sample-hystrix-aggregate application at http://localhost:8989/turbine.stream?cluster=SAMPLE-HYSTRIX-AGGREGATE
* A sample UI is available at http://localhost:8080

On Docker
~~~~~~~~~

Running using Docker is even simpler, assuming that docker-compose and docker are installed on your box, just run the following:

.Build the docker images for the microservices
[source,java]
----
mvn clean package docker:build
----

.Start up Docker containers
[source,java]
----
docker-compose up
----

If all the applications have come up cleanly, the following endpoints are available:

* Endpoints of the gateway application which forwards requests to the sample-hystrix-aggregate: Try http://dockerip:8080/sample-hystrix-aggregate/hello
* Eureka endpoint at http://dockerip:8761
* Hystrix dashboard at http://dockerip:8989/hystrix
* Turbine stream which aggregates information from sample-hystrix-aggregate application at http://dockerip:8989/turbine.stream?cluster=SAMPLE-HYSTRIX-AGGREGATE
* A sample UI is available at http://dockerip:8080




